export enum ConfigEnum {
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',
  DB_LOGGING = 'DB_LOGGING',
  DB_ENTITIES = 'DB_ENTITIES',
  DB_TYPE = 'DB_TYPE',
}
